<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INDHYDELP033" name="practise.AppiumFramework.Ecommerce_tc_3_test" tests="4" failures="0" timestamp="2020-12-10T17:38:54 IST" time="185.566" errors="4">
  <testcase name="Validation" time="59.049" classname="practise.AppiumFramework.Ecommerce_tc_3_test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at practise.AppiumFramework.Ecommerce_tc_3_test.Validation(Ecommerce_tc_3_test.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Validation -->
  <system-out/>
  <testcase name="Validation" time="61.506" classname="practise.AppiumFramework.Ecommerce_tc_3_test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at practise.AppiumFramework.Ecommerce_tc_3_test.Validation(Ecommerce_tc_3_test.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Validation -->
  <system-out/>
  <testcase name="Validation" time="1.516" classname="practise.AppiumFramework.Ecommerce_tc_3_test">
    <error type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: &lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
&lt;meta charset=&quot;utf-8&quot;&gt;
&lt;title&gt;Error&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;pre&gt;Error: EPIPE: broken pipe, write&lt;br&gt; &amp;nbsp; &amp;nbsp;at Socket._write (internal/net.js:62:25)&lt;br&gt; &amp;nbsp; &amp;nbsp;at doWrite (_stream_writable.js:441:12)&lt;br&gt; &amp;nbsp; &amp;nbsp;at writeOrBuffer (_stream_writable.js:425:5)&lt;br&gt; &amp;nbsp; &amp;nbsp;at Socket.Writable.write (_stream_writable.js:316:11)&lt;br&gt; &amp;nbsp; &amp;nbsp;at Console.log (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\transports\console.js:79:23)&lt;br&gt; &amp;nbsp; &amp;nbsp;at Console._write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\index.js:102:17)&lt;br&gt; &amp;nbsp; &amp;nbsp;at doWrite (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:428:64)&lt;br&gt; &amp;nbsp; &amp;nbsp;at writeOrBuffer (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:417:5)&lt;br&gt; &amp;nbsp; &amp;nbsp;at Console.Writable.write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:334:11)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.ondata (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:681:20)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.emit (events.js:311:20)&lt;br&gt; &amp;nbsp; &amp;nbsp;at addChunk (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:298:12)&lt;br&gt; &amp;nbsp; &amp;nbsp;at readableAddChunk (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:280:11)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.Readable.push (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:241:10)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.Transform.push (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:139:32)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger._transform (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:305:12)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.Transform._read (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:177:10)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.Transform._write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:164:83)&lt;br&gt; &amp;nbsp; &amp;nbsp;at doWrite (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:409:139)&lt;br&gt; &amp;nbsp; &amp;nbsp;at writeOrBuffer (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:398:5)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.Writable.write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:307:11)&lt;br&gt; &amp;nbsp; &amp;nbsp;at DerivedLogger.&amp;lt;computed&amp;gt; [as info] (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\create-logger.js:81:14)&lt;/pre&gt;
&lt;/body&gt;
&lt;/html&gt;

Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;INDHYDELP033&#039;, ip: &#039;192.168.56.1&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_201&#039;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: EPIPE: broken pipe, write<br> &nbsp; &nbsp;at Socket._write (internal/net.js:62:25)<br> &nbsp; &nbsp;at doWrite (_stream_writable.js:441:12)<br> &nbsp; &nbsp;at writeOrBuffer (_stream_writable.js:425:5)<br> &nbsp; &nbsp;at Socket.Writable.write (_stream_writable.js:316:11)<br> &nbsp; &nbsp;at Console.log (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\transports\console.js:79:23)<br> &nbsp; &nbsp;at Console._write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\index.js:102:17)<br> &nbsp; &nbsp;at doWrite (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:428:64)<br> &nbsp; &nbsp;at writeOrBuffer (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:417:5)<br> &nbsp; &nbsp;at Console.Writable.write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:334:11)<br> &nbsp; &nbsp;at DerivedLogger.ondata (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:681:20)<br> &nbsp; &nbsp;at DerivedLogger.emit (events.js:311:20)<br> &nbsp; &nbsp;at addChunk (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:298:12)<br> &nbsp; &nbsp;at readableAddChunk (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:280:11)<br> &nbsp; &nbsp;at DerivedLogger.Readable.push (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:241:10)<br> &nbsp; &nbsp;at DerivedLogger.Transform.push (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:139:32)<br> &nbsp; &nbsp;at DerivedLogger._transform (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:305:12)<br> &nbsp; &nbsp;at DerivedLogger.Transform._read (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:177:10)<br> &nbsp; &nbsp;at DerivedLogger.Transform._write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:164:83)<br> &nbsp; &nbsp;at doWrite (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:409:139)<br> &nbsp; &nbsp;at writeOrBuffer (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:398:5)<br> &nbsp; &nbsp;at DerivedLogger.Writable.write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:307:11)<br> &nbsp; &nbsp;at DerivedLogger.&lt;computed&gt; [as info] (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\create-logger.js:81:14)</pre>
</body>
</html>

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'INDHYDELP033', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
at practise.AppiumFramework.base.capabilities(base.java:79)
at practise.AppiumFramework.Ecommerce_tc_3_test.Validation(Ecommerce_tc_3_test.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 42 more
Caused by: org.openqa.selenium.WebDriverException: Unable to parse remote response: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: EPIPE: broken pipe, write<br> &nbsp; &nbsp;at Socket._write (internal/net.js:62:25)<br> &nbsp; &nbsp;at doWrite (_stream_writable.js:441:12)<br> &nbsp; &nbsp;at writeOrBuffer (_stream_writable.js:425:5)<br> &nbsp; &nbsp;at Socket.Writable.write (_stream_writable.js:316:11)<br> &nbsp; &nbsp;at Console.log (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\transports\console.js:79:23)<br> &nbsp; &nbsp;at Console._write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\index.js:102:17)<br> &nbsp; &nbsp;at doWrite (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:428:64)<br> &nbsp; &nbsp;at writeOrBuffer (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:417:5)<br> &nbsp; &nbsp;at Console.Writable.write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:334:11)<br> &nbsp; &nbsp;at DerivedLogger.ondata (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:681:20)<br> &nbsp; &nbsp;at DerivedLogger.emit (events.js:311:20)<br> &nbsp; &nbsp;at addChunk (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:298:12)<br> &nbsp; &nbsp;at readableAddChunk (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:280:11)<br> &nbsp; &nbsp;at DerivedLogger.Readable.push (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_readable.js:241:10)<br> &nbsp; &nbsp;at DerivedLogger.Transform.push (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:139:32)<br> &nbsp; &nbsp;at DerivedLogger._transform (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:305:12)<br> &nbsp; &nbsp;at DerivedLogger.Transform._read (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:177:10)<br> &nbsp; &nbsp;at DerivedLogger.Transform._write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_transform.js:164:83)<br> &nbsp; &nbsp;at doWrite (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:409:139)<br> &nbsp; &nbsp;at writeOrBuffer (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:398:5)<br> &nbsp; &nbsp;at DerivedLogger.Writable.write (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\node_modules\readable-stream\lib\_stream_writable.js:307:11)<br> &nbsp; &nbsp;at DerivedLogger.&lt;computed&gt; [as info] (C:\Users\Satyawand\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\create-logger.js:81:14)</pre>
</body>
</html>

at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
... 47 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'INDHYDELP033', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: AndroidDriver
at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)
at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)
at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
at org.openqa.selenium.json.Json.toType(Json.java:69)
at org.openqa.selenium.json.Json.toType(Json.java:55)
at org.openqa.selenium.json.Json.toType(Json.java:50)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)
... 47 more
]]>
    </error>
  </testcase> <!-- Validation -->
  <system-out/>
  <testcase name="Validation" time="63.495" classname="practise.AppiumFramework.Ecommerce_tc_3_test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at practise.AppiumFramework.Ecommerce_tc_3_test.Validation(Ecommerce_tc_3_test.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Validation -->
  <system-out/>
</testsuite> <!-- practise.AppiumFramework.Ecommerce_tc_3_test -->
